# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Specialty', models.CharField(max_length=100)),
                ('maxCap', models.IntegerField(default=0)),
                ('foodAvailable', models.BooleanField()),
                ('shelterAvailable', models.BooleanField()),
                ('hygenicAvailable', models.BooleanField()),
                ('counselingAvailable', models.BooleanField()),
                ('otherAvailable', models.BooleanField()),
                ('otherDetails', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
