# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='Email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
