# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelters', '0002_shelter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='counselingAvailable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='foodAvailable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='hygenicAvailable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='otherAvailable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='otherDetails',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='shelterAvailable',
            field=models.NullBooleanField(),
        ),
    ]
