# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelters', '0003_auto_20161022_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='place_id',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
