# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelters', '0005_auto_20161022_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='Specialty',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='otherAvailable',
        ),
        migrations.AddField(
            model_name='shelter',
            name='Description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
