# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shelters', '0006_auto_20161022_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='currCap',
            field=models.IntegerField(default=0),
        ),
    ]
