# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Title',
            field=models.CharField(default='request', max_length=100),
        ),
    ]
